---
title: "Apache Hop 2.18.1 is available!!"
date: 2026-06-18T06:44:56+02:00
authors: ["hansva"]
categories: ["2.18.1", "Release", "Apache Hop"]
preview: "Apache Hop 2.18.1 Released"
description: "The latest Apache Hop release 2.18.1 is now available. Let's walk through the most important new features in this release."
---

:imagesdir: ../../../../../static

:toc: macro
:toclevels: 3
:toc-title: Let's take a closer look at what Hop 2.18.1 brings:
:toc-class: none

The Apache Hop community is excited to announce the release of Apache Hop 2.18.1!

This is a patch release to address some regressions that have happened between 2.17.0 and 2.18.0.
The following issues have been solved:

- Text file input no longer returned row numbers if configured to return those
- Merge Rows (diff) regression with row lay-out
- Get file names filter on type (files/Folders) did not work anymore
- Sorted merge NPE when using multiple copies
- PGP Encrypt NPE
- Metadata injection transform regressions


This is your project. Your contributions shape what Apache Hop becomes.

or https://hop.apache.org/download/[**download Hop 2.18.1**] right away.


== Get Apache Hop 2.18.1 today!

Don't wait to try the latest and greatest version of Apache Hop. +
https://hop.apache.org/download/[Download 2.18.1 now] and experience the new features and improvements firsthand.

== GitHub Issues

This release contains work on 16 tickets.
Want to see every fix and enhancement? +
Explore the https://github.com/apache/hop/milestone/22?closed=1[Apache Hop 2.18 Milestone] and the https://github.com/apache/hop/releases/tag/2.18.1-rc1[Release notes^] on GitHub.

== Looking forward

The Apache Hop community is already working hard on the next version, packed with even more features and improvements you won't want to miss.

Thank you for being part of the Apache Hop journey.
