site:
  title: Apache Hop
  url: https://hop.apache.org
  start_page: manual::index.adoc

asciidoc:
  extensions:
  - '@asciidoctor/tabs'

antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true

content:
  sources:
  - url: git@github.com:apache/hop.git
    branches: 
      - main
      - release2.0.0
      - release2.1.0
      - release/2.2.0
      - release/2.3.0
      - release/2.4.0
      - release/2.5.0
      - release/2.6.0
      - release/2.7.0
      - release/2.8.0
      - release/2.9.0
      - release/2.10.0
      - release/2.11.0
      - release/2.12.0
      - release/2.13.0
      - release/2.14.0
      - release/2.15.0
    start_path: /docs/hop-user-manual/
  - url: git@github.com:apache/hop.git
    branches: 
      - main
      - release/2.5.0
      - release/2.6.0
      - release/2.7.0
      - release/2.8.0
      - release/2.9.0
      - release/2.10.0
      - release/2.11.0
      - release/2.12.0
      - release/2.13.0
      - release/2.14.0
      - release/2.15.0
    start_path: /docs/hop-tech-manual/
  - url: git@github.com:apache/hop.git
    branches: 
      - main
      - release/2.5.0
      - release/2.6.0
      - release/2.7.0
      - release/2.8.0
      - release/2.9.0
      - release/2.10.0
      - release/2.11.0
      - release/2.12.0
      - release/2.13.0
      - release/2.14.0
      - release/2.15.0
    start_path: /docs/hop-dev-manual/
    
ui:
  bundle:
    url: ./antora-ui-hop/build/ui-bundle.zip

urls:
  redirect_facility: disabled
  latest_version_segment: latest
  latest_prerelease_version_segment: next

output:
  clean: true
  dir: ./documentation

runtime: 
  fetch: true  

