---
title: "Tools"
---

The following tools are used within the Hop community.

* <<github, Github>>
* <<jira, Jira>>
* <<jenkins, Jenkins>>
* <<artifactory, Artifactory>>
* <<sonarcloud, Sonarcloud>>
* <<wiki, Wiki>>
* <<forum, Forum>>
* <<chat, Mattermost Chat>>

== anchor:github[]GitHub
All our source code is publicly available on GitHub, GitHub is a Git repository hosting service, but it adds many of its own features. While Git is a command line tool, GitHub provides a Web-based graphical interface. It also provides access control and several collaboration features.

Our repositories can be found https://github.com/project-hop[here , window="_blank"]

While GitHub provides solutions to do issue tracking we use a separate platform for this.

== anchor:jira[]Jira

All new features and issues found in Hop can be reported in our bug tracker. If you find an issue or want to request new features first read our link:/community/contribution-guides/jira-guide/[Jira-guide] this document contains the basic steps needed to create a ticket that we can work on.

To see what we are currently working on visit our https://project-hop.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=HOP[Jira Board , window="_blank"]

== anchor:jenkins[]Jenkins
Jenkins is a Continuous Integration/Deployment platform, when a commit has been made and source code is changed Jenkins will automatically trigger and test and build the code. It will also check pull requests. Our current Jenkins setup is a fairly basic workflow which will be extended in the future to include more checks and steps.

You can follow and see the status of all build project on our https://jenkins.project-hop.org[Jenkins Website]

== anchor:artifactory[]Artifactory
Artifactory is a storage location for artifacts that are created by maven. Each Jenkins build will push Artifacts to artifactory, you can then include these artifacts in your own projects.

Artifactyory can be found https://artifactory.project-hop.org[here]

== anchor:sonarcloud[]Sonarcloud
Sonarcloud is a platform that does code checks and validates the quality of your code. The goal of project hop is to create solid clean code, Sonarcloud helps us achieve this goal. Currently it does not look good yet but we are still in a stage where we are refactoring and cleaning up the Hop code base.

You can take a look at the status of our project https://sonarcloud.io/dashboard?id=hop[here]

== anchor:wiki[]Wiki

All documentation is written in Wiki style documents and resides in it's own repository or close to the code, this means all our documentation is version controlled and we have an easy and fast system to accept contributions from the community. More information on documentation contribution and guidelines can be found link:/community/contribution-guides/documentation-contribution-guide/[here].

== anchor:forum[]Forum

For user with questions we created a stack overflow like question board. It allows everyone to ask a question and a voting and acceptance system for the answers. The forum can be found https://forums.project-hop.org[here , window="_blank"].

== anchor:chat[]Mattermost Chat

Mattermost is a chat client that is comparable to Slack it is an opensource alternative that allows us to invite everyone to come join us and chat with the developers or ask question, feel free to join and start https://chat.project-hop.org[chatting , window="_blank"].