---
title: "Tools"
---

The following tools are used within the Hop community.

* <<github, Github>>
* <<Github-Issues, GitHub Issues>>
* <<Github-Discussions, GitHub Discussions>>
* <<jenkins, Jenkins>>
* <<sonarcloud, Sonarcloud>>
* <<wiki, Wiki>>
* <<chat, Slack>>

== anchor:github[]GitHub
All our source code is publicly available on GitHub, GitHub is a Git repository hosting service, but it adds many of its own features. While Git is a command line tool, GitHub provides a Web-based graphical interface. It also provides access control and several collaboration features.

Our repositories can be found https://github.com/apache/hop[here , window="_blank"]

While GitHub provides solutions to do issue tracking we use a separate platform for this.

== anchor:Github-Issues[]GitHub Issues

All new features and issues found in Hop can be reported in our bug tracker. If you find an issue or want to request new features first read our link:/community/contribution-guides/github-guide/[github-guide] this document contains the basic steps needed to create a ticket that we can work on.

To see what we are currently working on visit our https://github.com/apache/hop/issues[GitHub Issues page , window="_blank"]

== anchor:Github-Discussions[]GitHub Discussions

If you have questions or want to discuss new potential features but you don't like to use one of our mailing lists then you can also reach out to us using GitHub Discussions. 

To see what is currently being discussed visit our https://github.com/apache/hop/discussions[GitHub Discussions page , window="_blank"]

== anchor:jenkins[]Jenkins
Jenkins is a Continuous Integration/Deployment platform, when a commit has been made and source code is changed Jenkins will automatically trigger and test and build the code. It will also check pull requests. Our current Jenkins setup is a fairly basic workflow which will be extended in the future to include more checks and steps.

You can follow and see the status of all build project on our https://ci-builds.apache.org/job/Hop/[Jenkins Website]

== anchor:sonarcloud[]Sonarcloud
Sonarcloud is a platform that does code checks and validates the quality of your code. The goal of Apache Hop is to create solid clean code, Sonarcloud helps us achieve this goal. Currently it does not look good yet but we are still in a stage where we are refactoring and cleaning up the Hop code base.

You can take a look at the status of our project https://sonarcloud.io/dashboard?id=apache_hop[here]

== anchor:wiki[]Wiki

All documentation is written in Wiki style documents and resides in it's own repository or close to the code, this means all our documentation is version controlled and we have an easy and fast system to accept contributions from the community. More information on documentation contribution and guidelines can be found link:/community/contribution-guides/documentation-contribution-guide/[here].

== anchor:chat[]Slack

The Apache Hop team has a channel on the http://the-asf.slack.com/[ASF Slack server]. If you already have a multi-channel account you can join the conversations in the #hop channel. If you have an @apache.org email address you can join using that address. If you don't you can request an invite by sending a mail to our link:/community/mailing-list/[users mailing list].
