---
title: "Translation Contribution Guide"
---

Translating Apache Hop to your language is an easy and code free contribution that adds a lot of value to our user community.
We use an online application called https://weblate.org/en/[Weblate] to help us in translating Hop.


== anchor:hop-translator[]Hop Translation Website

To help translate Hop you can visit https://translate.project-hop.org/[https://translate.project-hop.org/]

For more information on how to use Weblate you can read the https://docs.weblate.org/en/latest/user/translating.html[guides] provided on their site.

== anchor:hop-translator-how-to-run[]Supported languages
The current list of languages that can be translated is:

- Chinese
- Dutch
- French
- German
- Italian
- Japanese
- Korean
- Norwegian
- Polish
- Portuguese (Brazil)
- Portuguese (Portugal)
- Spanish
- Spanish (Argentina)

Once a language reaches a threshold of about 70% we mark it as no longer being a beta language and new users in that region will get the language by default when launching Hop.

If you would like to start translating Hop in a language that is not yet in the list, file a feature request ticket and we will add the language to the list.