---
title: "Website Contribution Guide"
---

The website is the central place and first point of entry for any potentially new user. It needs to contain as much information as possible but not scare away new users with complex structures. This guide explains how to contribute to the website.


. <<obtain-website, Obtain the documentation sources>>
. <<before-start, Before you start start working on the documentation...>>
. <<update-or-extend, Update or extend the documentation>>
. <<multi-lang-website, Documentation translations>>
. <<submit-website, Submit your contribution>>



== anchor:obtain-website[]Obtain the Website sources

The easiest way to contribute website changes is to fork Hop’s repository on GitHub into your own GitHub account by clicking on the fork button at the top right. If you have no GitHub account, you can create one for free.

Next, clone your fork to your local machine.

[frame=topbot]
|===
|git clone https://github.com/<your-user-name>/hop-website.git
|===


== anchor:before-start[]Before you start start working on the documentation...

… please make sure there exists a Jira issue that corresponds to your contribution. We require all website changes to refer to a Jira issue, except for trivial fixes such as typos.

== anchor:update-or-extend[]Update or extend the documentation

The Hop website is written in Nodejs and Asciidoc. Asciidoc is a lightweight markup language which can be translated to HTML.

The instructions on how to locally build and preview the website are written on the github page you can find them https://github.com/project-hop/hop-website/blob/master/README.md[here].

In order to update or extend the website content you have to modify the Asciidoc (.adoc) files.
For more information on Asciidoc check out http://asciidoc.org/[this] website.

Please feel free to ask any questions you have on the developer chat channel.


== anchor:multi-lang-website[] Documentation translations

We are planning on providing the website in multiple languages. We are looking for contributors that want to work with us and make this possible! If you are interested to maintain a translation language feel free to contact us on our https://chat.project-hop.org[chat].



== anchor:submit-website[]Submit your contribution

Project Hop accepts website contributions through the GitHub as Pull Requests. Pull requests are a simple way of offering a patch by providing a pointer to a code branch that contains the changes.

To prepare and submit a pull request follow these steps.

Commit your changes to your local git repository. The commit message should point to the corresponding Jira issue by starting with [HOP-XXXX].

Push your committed contribution to your fork of the Hop repository at GitHub.

git push origin myBranch

Go to the website of your repository fork (https://github.com/<your-user-name>/hop-doc) and use the “Create Pull Request” button to start creating a pull request. Make sure that the base fork is hop master and the head fork selects the branch with your changes. Give the pull request a meaningful description and submit it.

It is also possible to attach a patch to a Jira issue.
