#!/usr/bin/env node
// Licensed to the Apache Software Foundation (ASF) under one or more
// contributor license agreements.  See the NOTICE file distributed with
// this work for additional information regarding copyright ownership.
// The ASF licenses this file to You under the Apache License, Version 2.0
// (the "License"); you may not use this file except in compliance with
// the License.  You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*
 * Generate the Antora header and footer partials from src/data/nav.mjs.
 *
 * The split means two template systems render the same chrome. The previous
 * site had the same problem and the two copies drifted until the footers were
 * asserting different copyright holders. The links now live in one file and
 * this writes the Handlebars side, so drift is not possible without someone
 * editing a file marked as generated.
 */

import { writeFileSync } from 'node:fs'
import { mainNav, footerNav, socials, downloadCta } from '../src/data/nav.mjs'

const HEADER = `{{!
    GENERATED by tools/sync-nav.mjs from src/data/nav.mjs - do not edit.

    Licensed to the Apache Software Foundation (ASF) under one or more
    contributor license agreements.  See the NOTICE file distributed with
    this work for additional information regarding copyright ownership.
    The ASF licenses this file to You under the Apache License, Version 2.0
    (the "License"); you may not use this file except in compliance with
    the License.  You may obtain a copy of the License at

         http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
}}`

const chev = '<svg class="chev" width="10" height="10" viewBox="0 0 10 10" aria-hidden="true"><path d="M1 3l4 4 4-4" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linecap="round" stroke-linejoin="round"/></svg>'
const href = (h) => (h.startsWith('http') ? h : `{{siteRootPath}}${h}`)

const navItems = mainNav.map((item) => {
  if (!item.children) {
    return `        <li><a href="${href(item.href)}"${item.cta ? ' class="mainnav__cta"' : ''}>${item.label}</a></li>`
  }
  const children = item.children
    .map((c) => `            <li><a href="${href(c.href)}">${c.label}</a></li>`)
    .join('\n')
  return `        <li class="has-menu">
          <button type="button" class="mainnav__toggle" aria-expanded="false" aria-controls="menu-${item.id}">
            ${item.label} ${chev}
          </button>
          <ul class="submenu" id="menu-${item.id}">
${children}
          </ul>
        </li>`
}).join('\n')

const socialIcons = socials.map((s) =>
  `        <a class="icon-btn" href="${s.href}" aria-label="Apache Hop on ${s.label}" title="${s.label}"><svg width="16" height="16" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="${s.path}"/></svg></a>`
).join('\n')

const footerSocials = socials.map((s) =>
  `        <li><a href="${s.href}" aria-label="Apache Hop on ${s.label}" title="${s.label}"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="${s.path}"/></svg></a></li>`
).join('\n')

const header = `${HEADER}
<a class="skip-link" href="#main" data-pagefind-ignore>Skip to main content</a>
<header class="site-header" data-pagefind-ignore>
  <div class="site-header__inner">
    <a class="brand" href="{{siteRootPath}}/" aria-label="Apache Hop home">
      <img src="{{siteRootPath}}/img/hop-logo.svg" alt="" width="34" height="34" aria-hidden="true">
      <span class="brand__name">Apache Hop</span>
    </a>

    <nav class="mainnav" id="mainnav" aria-label="Main">
      <ul class="mainnav__list">
${navItems}
      </ul>
    </nav>

    <div class="header-tools">
      <div class="search" role="search">
        <label class="visually-hidden" for="search-input">Search Apache Hop</label>
        <input id="search-input" type="search" placeholder="Search" autocomplete="off">
      </div>
      <span class="socials">
${socialIcons}
      </span>
      <a class="mainnav__cta" href="{{siteRootPath}}${downloadCta.href}">${downloadCta.label}</a>
      <button type="button" id="theme-toggle" class="icon-btn" aria-label="Switch theme" title="Switch theme">
        <svg class="icon-sun" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>
        <svg class="icon-moon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M21 12.8A9 9 0 1111.2 3a7 7 0 009.8 9.8z"/></svg>
      </button>
      <button type="button" id="nav-burger" class="icon-btn burger" aria-expanded="false" aria-controls="mainnav" aria-label="Open menu">
        <span></span><span></span><span></span>
      </button>
    </div>
  </div>
</header>
`

const columns = footerNav.map((col) => `      <div>
        <h2>${col.title}</h2>
        <ul>
${col.links.map((l) => `          <li><a href="${href(l.href)}">${l.label}</a></li>`).join('\n')}
        </ul>
      </div>`).join('\n')

const footer = `${HEADER}
<footer class="site-footer" data-pagefind-ignore>
  <div class="site-footer__inner">
    <div class="site-footer__brand">
      <img src="{{siteRootPath}}/img/hop-logo.svg" alt="" width="30" height="30" aria-hidden="true">
      <div>
        <p>The Hop Orchestration Platform &mdash; visual data and metadata orchestration, designed once and run anywhere.</p>
        <ul class="site-footer__socials">
${footerSocials}
        </ul>
      </div>
    </div>
    <nav class="site-footer__nav" aria-label="Footer">
${columns}
    </nav>
  </div>
  <div class="site-footer__legal">
    <p>
      Copyright &copy; 2019&ndash;{{year}} <a href="https://www.apache.org/">The Apache Software Foundation</a>,
      licensed under the <a href="https://www.apache.org/licenses/">Apache License, Version 2.0</a>.
    </p>
    <p>
      Apache, Apache Hop, Hop, and the Apache feather logo are either registered trademarks or
      trademarks of the Apache Software Foundation in the United States and/or other countries.
    </p>
  </div>
</footer>

<script src="{{siteRootPath}}/js/site.js"></script>
<script src="{{uiRootPath}}/js/tabs.js"></script>
`

writeFileSync('ui/partials/header.hbs', header)
writeFileSync('ui/partials/footer.hbs', footer)
console.log('sync-nav: wrote ui/partials/header.hbs and ui/partials/footer.hbs from src/data/nav.mjs')
